%global tl_name hyphen-romanian
%global tl_revision 78069

Name:		texlive-%{tl_name}
Version:	%{tl_revision}
Release:	1
Summary:	Romanian hyphenation patterns.
Group:		Publishing
URL:		https://www.ctan.org/pkg/hyphen-romanian
License:	LPPL
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/hyphen-romanian.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Requires:	texlive(hyph-utf8)
Requires:	texlive(hyphen-base)
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
Hyphenation patterns for Romanian in T1/EC and UTF-8 encodings. The
UTF-8 patterns use U+0219 for the character 's with comma accent' and
U+021B for 't with comma accent', but we may consider using U+015F and
U+0163 as well in the future. Generated by PatGen2-output hyphen-level
9.

